favicon: /favicon.ico

store_url: https://item.taobao.com/item.htm?id=559967623589

weibo_url: http://weibo.com/stickeroverflow

background: "//ox374gfao.bkt.clouddn.com/E996C845-C672-47F4-A418-E0DEBCA88296-4957-00000257C9BD5FF1_tmp.JPG"

stickers:
  - name: Webpack
    license:
    license_from: https://github.com/webpack/media/blob/master/LICENSE
    img: webpack.png
  - name: Gulp
    license: CC 0
    license_from:
    img: gulp.png
  - name: Vue
    license: CC BY 4.0
    license_from: https://github.com/vuejs/art/
    img: vue.png
  - name: Bower
    license:
    license_from: https://bower.io/docs/about/
    img: bower.png
  - name: Babel
    license: MIT
    license_from: https://github.com/babel/logo/blob/master/LICENSE
    img: babel.png
  - name: Angular
    license: CC BY 4.0
    license_from: https://angular.io/presskit
    img: angular.png
  - name: React
    license:
    license_from:  https://worldvectorlogo.com/zh/terms-of-use
  - name: JS
    license: MIT
    license_from: https://github.com/voodootikigod/logo.js/blob/master/LICENSE
  - name: Docker
    license:
    license_from: https://www.docker.com/brand-guidelines
  - name: TS
    license: MIT
    license_from: https://github.com/remojansen/logo.ts/blob/master/LICENSE
  - name: VS Code
    license: No License
    license_from: https://github.com/auchenberg/vscode-logo-svg
  - name: Git
    license: CC BY 3.0
    license_from: https://git-scm.com/downloads/logos